### ISSUE TITLE
Updating chrome.* intellisense files

### ISSUE THREAD

**Issue by adityabhaskar** [cmc19/js-intellisense#2]
Hi

Thanks a lot for the intellisense file for chrome.* APIs.

The file hasn't been updated in a while. Do you have a script you used for updating it? Or would you be able to share the steps for creating the file from source, so I can update it and send a PR?

Cheers!

Adi

**Comment by tellok** [comment]
yep, indeed need an update

**Comment by tellok** [comment]
add following text in `jsconfig.json` solves the problem, no need to inlcude this intellisense file
```json
{
  "typeAcquisition": {
    "include": [
      "chrome"
    ]
  }
}
``
